const advancedLineupColumns = [
    { label: "GROUP SET", accessor: "group_set" },
    { label: "GROUP ID", accessor: "group_id" },
    { label: "GROUP NAME", accessor: "group_name" },
    { label: "TEAM ID", accessor: "team_id" },
    { label: "TEAM ABBREVIATION", accessor: "team_abbreviation" },
    { label: "GP", accessor: "gp" },
    { label: "W", accessor: "w" },
    { label: "L", accessor: "l" },
    { label: "W PCT", accessor: "w_pct" },
    { label: "MIN", accessor: "min" },
    { label: "E OFF RATING", accessor: "e_off_rating" },
    { label: "OFF RATING", accessor: "off_rating" },
    { label: "E DEF RATING", accessor: "e_def_rating" },
    { label: "DEF RATING", accessor: "def_rating" },
    { label: "E NET RATING", accessor: "e_net_rating" },
    { label: "NET RATING", accessor: "net_rating" },
    { label: "AST PCT", accessor: "ast_pct" },
    { label: "AST TO", accessor: "ast_to" },
    { label: "AST RATIO", accessor: "ast_ratio" },
    { label: "OREB PCT", accessor: "oreb_pct" },
    { label: "DREB PCT", accessor: "dreb_pct" },
    { label: "REB PCT", accessor: "reb_pct" },
    { label: "TM TOV PCT", accessor: "tm_tov_pct" },
    { label: "EFG PCT", accessor: "efg_pct" },
    { label: "TS PCT", accessor: "ts_pct" },
    { label: "E PACE", accessor: "e_pace" },
    { label: "PACE", accessor: "pace" },
    { label: "PACE PER40", accessor: "pace_per40" },
    { label: "POSS", accessor: "poss" },
    { label: "PIE", accessor: "pie" },
    { label: "GP RANK", accessor: "gp_rank" },
    { label: "W RANK", accessor: "w_rank" },
    { label: "L RANK", accessor: "l_rank" },
    { label: "W PCT RANK", accessor: "w_pct_rank" },
    { label: "MIN RANK", accessor: "min_rank" },
    { label: "OFF RATING RANK", accessor: "off_rating_rank" },
    { label: "DEF RATING RANK", accessor: "def_rating_rank" },
    { label: "NET RATING RANK", accessor: "net_rating_rank" },
    { label: "AST PCT RANK", accessor: "ast_pct_rank" },
    { label: "AST TO RANK", accessor: "ast_to_rank" },
    { label: "AST RATIO RANK", accessor: "ast_ratio_rank" },
    { label: "OREB PCT RANK", accessor: "oreb_pct_rank" },
    { label: "DREB PCT RANK", accessor: "dreb_pct_rank" },
    { label: "REB PCT RANK", accessor: "reb_pct_rank" },
    { label: "TM TOV PCT RANK", accessor: "tm_tov_pct_rank" },
    { label: "EFG PCT RANK", accessor: "efg_pct_rank" },
    { label: "TS PCT RANK", accessor: "ts_pct_rank" },
    { label: "PACE RANK", accessor: "pace_rank" },
    { label: "PIE RANK", accessor: "pie_rank" }
]

const advancedPlayerColumns = [
    { label: "NAME", accessor: "name" },
    { label: "TEAM", accessor: "team_abbreviation" },
    { label: "TM TOV PCT", accessor: "season" },
    { label: "MIN", accessor: "min" },
    { label: "AST PCT", accessor: "ast_pct" },
    { label: "AST RATIO", accessor: "ast_ratio" },
    { label: "AST TO", accessor: "ast_to" },
    { label: "DEF RATING", accessor: "def_rating" },
    { label: "DEF REB PCT", accessor: "dreb_pct" },
    { label: "EFG PCT", accessor: "efg_pct" },
    { label: "GP", accessor: "gp" },
    { label: "NET RATING", accessor: "net_rating" },
    { label: "OFF RATING", accessor: "off_rating" },
    { label: "OREB PCT", accessor: "oreb_pct" },
    { label: "PACE", accessor: "pace" },
    { label: "REB PCT", accessor: "reb_pct" },
    { label: "TM TOV PCT", accessor: "tm_tov_pct" },
    { label: "TS PCT", accessor: "ts_pct" },
    { label: "USG PCT", accessor: "usg_pct" },
    { label: "POSS", accessor: "poss" },
    { label: "PIE", accessor: "pie" }
]

const basePlayerColumns = [
    { label: "GAME ID", accessor: "game_id" },
    { label: "TEAM ID", accessor: "team_id" },
    { label: "TEAM ABBREVIATION", accessor: "team_abbreviation" },
    { label: "TEAM CITY", accessor: "team_city" },
    { label: "PLAYER ID", accessor: "player_id" },
    { label: "PLAYER NAME", accessor: "player_name" },
    { label: "NICKNAME", accessor: "nickname" },
    { label: "START POSITION", accessor: "start_position" },
    { label: "COMMENT", accessor: "comment" },
    { label: "MIN", accessor: "min" },
    { label: "FGM", accessor: "fgm" },
    { label: "FGA", accessor: "fga" },
    { label: "FG%", accessor: "fg_pct" },
    { label: "FG3M", accessor: "fg3m" },
    { label: "FG3A", accessor: "fg3a" },
    { label: "FG3%", accessor: "fg3_pct" },
    { label: "FTM", accessor: "ftm" },
    { label: "FTA", accessor: "fta" },
    { label: "FT%", accessor: "ft_pct" },
    { label: "OREB", accessor: "oreb" },
    { label: "DREB", accessor: "dreb" },
    { label: "REB", accessor: "reb" },
    { label: "AST", accessor: "Ast" },
    { label: "STL", accessor: "stl" },
    { label: "BLK", accessor: "blk" },
    { label: "TOV", accessor: "tov" },
    { label: "PF", accessor: "pf" },
    { label: "PTS", accessor: "pts" },
    { label: "PLUS MINUS", accessor: "plus_minus" }
];

const baseLineupColumns = [
    { label: "GROUP SET", accessor: "group_set" },
    { label: "GROUP ID", accessor: "group_id" },
    { label: "GROUP NAME", accessor: "group_name" },
    { label: "TEAM ID", accessor: "team_id" },
    { label: "TEAM ABBREVIATION", accessor: "team_abbreviation" },
    { label: "GP", accessor: "gp" },
    { label: "W", accessor: "w" },
    { label: "L", accessor: "l" },
    { label: "W PCT", accessor: "w_pct" },
    { label: "MIN", accessor: "min" },
    { label: "FGM", accessor: "fgm" },
    { label: "FGA", accessor: "fga" },
    { label: "FG PCT", accessor: "fg_pct" },
    { label: "FG3M", accessor: "fg3m" },
    { label: "FG3A", accessor: "fg3a" },
    { label: "FG3 PCT", accessor: "fg3_pct" },
    { label: "FTM", accessor: "ftm" },
    { label: "FTA", accessor: "fta" },
    { label: "FT PCT", accessor: "ft_pct" },
    { label: "OREB", accessor: "oreb" },
    { label: "DREB", accessor: "dreb" },
    { label: "REB", accessor: "reb" },
    { label: "AST", accessor: "ast" },
    { label: "TOV", accessor: "tov" },
    { label: "STL", accessor: "stl" },
    { label: "BLK", accessor: "blk" },
    { label: "BLKA", accessor: "blka" },
    { label: "PF", accessor: "pf" },
    { label: "PFD", accessor: "pfd" },
    { label: "PTS", accessor: "pts" },
    { label: "PLUS MINUS", accessor: "plus_minus" },
    { label: "GP RANK", accessor: "gp_rank" },
    { label: "W RANK", accessor: "w_rank" },
    { label: "L RANK", accessor: "l_rank" },
    { label: "W PCT RANK", accessor: "w_pct_rank" },
    { label: "MIN RANK", accessor: "min_rank" },
    { label: "FGM RANK", accessor: "fgm_rank" },
    { label: "FGA RANK", accessor: "fga_rank" },
    { label: "FG PCT RANK", accessor: "fg_pct_rank" },
    { label: "FG3M RANK", accessor: "fg3m_rank" },
    { label: "FG3A RANK", accessor: "fg3a_rank" },
    { label: "FG3 PCT RANK", accessor: "fg3_pct_rank" },
    { label: "FTM RANK", accessor: "ftm_rank" },
    { label: "FTA RANK", accessor: "fta_rank" },
    { label: "FT PCT RANK", accessor: "ft_pct_rank" },
    { label: "OREB RANK", accessor: "oreb_rank" },
    { label: "DREB RANK", accessor: "dreb_rank" },
    { label: "REB RANK", accessor: "reb_rank" },
    { label: "AST RANK", accessor: "ast_rank" },
    { label: "TOV RANK", accessor: "tov_rank" },
    { label: "STL RANK", accessor: "stl_rank" },
    { label: "BLK RANK", accessor: "blk_rank" },
    { label: "BLKA RANK", accessor: "blka_rank" },
    { label: "PF RANK", accessor: "pf_rank" },
    { label: "PFD RANK", accessor: "pfd_rank" },
    { label: "PTS RANK", accessor: "pts_rank" },
    { label: "PLUS MINUS RANK", accessor: "plus_minus_rank" }
];


export { advancedLineupColumns, advancedPlayerColumns, basePlayerColumns, baseLineupColumns }