const scoringPlayerColumns = [
    { label: "GAME_ID", accessor: "game_id" },
    { label: "TEAM_ID", accessor: "team_id" },
    { label: "TEAM_ABBREVIATION", accessor: "team_abbreviation" },
    { label: "TEAM_CITY", accessor: "team_city" },
    { label: "PLAYER_ID", accessor: "player_id" },
    { label: "PLAYER_NAME", accessor: "player_name" },
    { label: "NICKNAME", accessor: "nickname" },
    { label: "START_POSITION", accessor: "start_position" },
    { label: "COMMENT", accessor: "comment" },
    { label: "MIN", accessor: "min" },
    { label: "PCT_FGA_2PT", accessor: "pct_fga_2pt" },
    { label: "PCT_FGA_3PT", accessor: "pct_fga_3pt" },
    { label: "PCT_PTS_2PT", accessor: "pct_pts_2pt" },
    { label: "PCT_PTS_2PT_MR", accessor: "pct_pts_2pt_mr" },
    { label: "PCT_PTS_3PT", accessor: "pct_pts_3pt" },
    { label: "PCT_PTS_FB", accessor: "pct_pts_fb" },
    { label: "PCT_PTS_FT", accessor: "pct_pts_ft" },
    { label: "PCT_PTS_OFF_TOV", accessor: "pct_pts_off_tov" },
    { label: "PCT_PTS_PAINT", accessor: "pct_pts_paint" },
    { label: "PCT_AST_2PM", accessor: "pct_ast_2pm" },
    { label: "PCT_UAST_2PM", accessor: "pct_uast_2pm" },
    { label: "PCT_AST_3PM", accessor: "pct_ast_3pm" },
    { label: "PCT_UAST_3PM", accessor: "pct_uast_3pm" },
    { label: "PCT_AST_FGM", accessor: "pct_ast_fgm" }
];

const miscPlayerColumns = [
    { label: "GAME_ID", accessor: "game_id" },
    { label: "TEAM_ID", accessor: "team_id" },
    { label: "TEAM_ABBREVIATION", accessor: "team_abbreviation" },
    { label: "TEAM_CITY", accessor: "team_city" },
    { label: "PLAYER_ID", accessor: "player_id" },
    { label: "PLAYER_NAME", accessor: "player_name" },
    { label: "NICKNAME", accessor: "nickname" },
    { label: "START_POSITION", accessor: "start_position" },
    { label: "COMMENT", accessor: "comment" },
    { label: "MIN", accessor: "min" },
    { label: "PTS_OFF_TOV", accessor: "pts_off_tov" },
    { label: "PTS_2ND_CHANCE", accessor: "pts_2nd_chance" },
    { label: "PTS_FB", accessor: "pts_fb" },
    { label: "PTS_PAINT", accessor: "pts_paint" },
    { label: "OPP_PTS_OFF_TOV", accessor: "opp_pts_off_tov" },
    { label: "OPP_PTS_2ND_CHANCE", accessor: "opp_pts_2nd_chance" },
    { label: "OPP_PTS_FB", accessor: "opp_pts_fb" },
    { label: "OPP_PTS_PAINT", accessor: "opp_pts_paint" },
    { label: "BLK", accessor: "blk" },
    { label: "BLKA", accessor: "blka" },
    { label: "PF", accessor: "pf" },
    { label: "PFD", accessor: "pfd" }
];

const fourFactorsPlayerColumns = [
    { label: "GAME_ID", accessor: "game_id" },
    { label: "TEAM_ID", accessor: "team_id" },
    { label: "TEAM_ABBREVIATION", accessor: "team_abbreviation" },
    { label: "TEAM_CITY", accessor: "team_city" },
    { label: "PLAYER_ID", accessor: "player_id" },
    { label: "PLAYER_NAME", accessor: "player_name" },
    { label: "NICKNAME", accessor: "nickname" },
    { label: "START_POSITION", accessor: "start_position" },
    { label: "COMMENT", accessor: "comment" },
    { label: "MIN", accessor: "min" },
    { label: "EFG_PCT", accessor: "efg_pct" },
    { label: "FTA_RATE", accessor: "fta_rate" },
    { label: "TM_TOV_PCT", accessor: "tm_tov_pct" },
    { label: "OREB_PCT", accessor: "oreb_pct" },
    { label: "OPP_EFG_PCT", accessor: "opp_efg_pct" },
    { label: "OPP_FTA_RATE", accessor: "opp_fta_rate" },
    { label: "OPP_TOV_PCT", accessor: "opp_tov_pct" },
    { label: "OPP_OREB_PCT", accessor: "opp_oreb_pct" }
];


const advancedPlayerColumns = [
    { label: "NAME", accessor: "player_name" },
    { label: "TEAM", accessor: "team_abbreviation" },
    { label: "MIN", accessor: "min" },
    { label: "OFF RATING", accessor: "off_rating" },
    { label: "DEF RATING", accessor: "def_rating" },
    { label: "NET RATING", accessor: "net_rating" },
    { label: "AST PCT", accessor: "ast_pct" },
    { label: "AST TOV", accessor: "ast_tov" },
    { label: "AST RATIO", accessor: "ast_ratio" },
    { label: "OREB PCT", accessor: "oreb_pct" },
    { label: "DEF REB PCT", accessor: "dreb_pct" },
    { label: "REB PCT", accessor: "reb_pct" },
    { label: "TOV PCT", accessor: "tov_pct" },
    { label: "EFG PCT", accessor: "efg_pct" },
    { label: "TS PCT", accessor: "ts_pct" },
    { label: "USG PCT", accessor: "usg_pct" },
    { label: "PACE", accessor: "pace" },
    { label: "POSS", accessor: "poss" },
    { label: "PIE", accessor: "pie" }
]

const basePlayerColumns = [
    { label: "GAME ID", accessor: "game_id" },
    { label: "TEAM ID", accessor: "team_id" },
    { label: "TEAM ABBREVIATION", accessor: "team_abbreviation" },
    { label: "TEAM CITY", accessor: "team_city" },
    { label: "PLAYER ID", accessor: "player_id" },
    { label: "PLAYER NAME", accessor: "player_name" },
    { label: "NICKNAME", accessor: "nickname" },
    { label: "START POSITION", accessor: "start_position" },
    { label: "COMMENT", accessor: "comment" },
    { label: "MIN", accessor: "min" },
    { label: "FGM", accessor: "fgm" },
    { label: "FGA", accessor: "fga" },
    { label: "FG%", accessor: "fg_pct" },
    { label: "FG3M", accessor: "fg3m" },
    { label: "FG3A", accessor: "fg3a" },
    { label: "FG3%", accessor: "fg3_pct" },
    { label: "FTM", accessor: "ftm" },
    { label: "FTA", accessor: "fta" },
    { label: "FT%", accessor: "ft_pct" },
    { label: "OREB", accessor: "oreb" },
    { label: "DREB", accessor: "dreb" },
    { label: "REB", accessor: "reb" },
    { label: "AST", accessor: "Ast" },
    { label: "STL", accessor: "stl" },
    { label: "BLK", accessor: "blk" },
    { label: "TOV", accessor: "tov" },
    { label: "PF", accessor: "pf" },
    { label: "PTS", accessor: "pts" },
    { label: "PLUS MINUS", accessor: "plus_minus" }
];

const advancedLineupColumns = [
    { label: "GROUP SET", accessor: "group_set" },
    { label: "GROUP ID", accessor: "group_id" },
    { label: "GROUP NAME", accessor: "group_name" },
    { label: "TEAM ID", accessor: "team_id" },
    { label: "TEAM ABBREVIATION", accessor: "team_abbreviation" },
    { label: "GP", accessor: "gp" },
    { label: "W", accessor: "w" },
    { label: "L", accessor: "l" },
    { label: "W PCT", accessor: "w_pct" },
    { label: "MIN", accessor: "min" },
    { label: "E OFF RATING", accessor: "e_off_rating" },
    { label: "OFF RATING", accessor: "off_rating" },
    { label: "E DEF RATING", accessor: "e_def_rating" },
    { label: "DEF RATING", accessor: "def_rating" },
    { label: "E NET RATING", accessor: "e_net_rating" },
    { label: "NET RATING", accessor: "net_rating" },
    { label: "AST PCT", accessor: "ast_pct" },
    { label: "AST TO", accessor: "ast_to" },
    { label: "AST RATIO", accessor: "ast_ratio" },
    { label: "OREB PCT", accessor: "oreb_pct" },
    { label: "DREB PCT", accessor: "dreb_pct" },
    { label: "REB PCT", accessor: "reb_pct" },
    { label: "TM TOV PCT", accessor: "tm_tov_pct" },
    { label: "EFG PCT", accessor: "efg_pct" },
    { label: "TS PCT", accessor: "ts_pct" },
    { label: "E PACE", accessor: "e_pace" },
    { label: "PACE", accessor: "pace" },
    { label: "PACE PER40", accessor: "pace_per40" },
    { label: "POSS", accessor: "poss" },
    { label: "PIE", accessor: "pie" },
    { label: "GP RANK", accessor: "gp_rank" },
    { label: "W RANK", accessor: "w_rank" },
    { label: "L RANK", accessor: "l_rank" },
    { label: "W PCT RANK", accessor: "w_pct_rank" },
    { label: "MIN RANK", accessor: "min_rank" },
    { label: "OFF RATING RANK", accessor: "off_rating_rank" },
    { label: "DEF RATING RANK", accessor: "def_rating_rank" },
    { label: "NET RATING RANK", accessor: "net_rating_rank" },
    { label: "AST PCT RANK", accessor: "ast_pct_rank" },
    { label: "AST TO RANK", accessor: "ast_to_rank" },
    { label: "AST RATIO RANK", accessor: "ast_ratio_rank" },
    { label: "OREB PCT RANK", accessor: "oreb_pct_rank" },
    { label: "DREB PCT RANK", accessor: "dreb_pct_rank" },
    { label: "REB PCT RANK", accessor: "reb_pct_rank" },
    { label: "TM TOV PCT RANK", accessor: "tm_tov_pct_rank" },
    { label: "EFG PCT RANK", accessor: "efg_pct_rank" },
    { label: "TS PCT RANK", accessor: "ts_pct_rank" },
    { label: "PACE RANK", accessor: "pace_rank" },
    { label: "PIE RANK", accessor: "pie_rank" }
]

const baseLineupColumns = [
    { label: "GROUP SET", accessor: "group_set" },
    { label: "GROUP ID", accessor: "group_id" },
    { label: "GROUP NAME", accessor: "group_name" },
    { label: "TEAM ID", accessor: "team_id" },
    { label: "TEAM ABBREVIATION", accessor: "team_abbreviation" },
    { label: "GP", accessor: "gp" },
    { label: "W", accessor: "w" },
    { label: "L", accessor: "l" },
    { label: "W PCT", accessor: "w_pct" },
    { label: "MIN", accessor: "min" },
    { label: "FGM", accessor: "fgm" },
    { label: "FGA", accessor: "fga" },
    { label: "FG PCT", accessor: "fg_pct" },
    { label: "FG3M", accessor: "fg3m" },
    { label: "FG3A", accessor: "fg3a" },
    { label: "FG3 PCT", accessor: "fg3_pct" },
    { label: "FTM", accessor: "ftm" },
    { label: "FTA", accessor: "fta" },
    { label: "FT PCT", accessor: "ft_pct" },
    { label: "OREB", accessor: "oreb" },
    { label: "DREB", accessor: "dreb" },
    { label: "REB", accessor: "reb" },
    { label: "AST", accessor: "ast" },
    { label: "TOV", accessor: "tov" },
    { label: "STL", accessor: "stl" },
    { label: "BLK", accessor: "blk" },
    { label: "BLKA", accessor: "blka" },
    { label: "PF", accessor: "pf" },
    { label: "PFD", accessor: "pfd" },
    { label: "PTS", accessor: "pts" },
    { label: "PLUS MINUS", accessor: "plus_minus" },
    { label: "GP RANK", accessor: "gp_rank" },
    { label: "W RANK", accessor: "w_rank" },
    { label: "L RANK", accessor: "l_rank" },
    { label: "W PCT RANK", accessor: "w_pct_rank" },
    { label: "MIN RANK", accessor: "min_rank" },
    { label: "FGM RANK", accessor: "fgm_rank" },
    { label: "FGA RANK", accessor: "fga_rank" },
    { label: "FG PCT RANK", accessor: "fg_pct_rank" },
    { label: "FG3M RANK", accessor: "fg3m_rank" },
    { label: "FG3A RANK", accessor: "fg3a_rank" },
    { label: "FG3 PCT RANK", accessor: "fg3_pct_rank" },
    { label: "FTM RANK", accessor: "ftm_rank" },
    { label: "FTA RANK", accessor: "fta_rank" },
    { label: "FT PCT RANK", accessor: "ft_pct_rank" },
    { label: "OREB RANK", accessor: "oreb_rank" },
    { label: "DREB RANK", accessor: "dreb_rank" },
    { label: "REB RANK", accessor: "reb_rank" },
    { label: "AST RANK", accessor: "ast_rank" },
    { label: "TOV RANK", accessor: "tov_rank" },
    { label: "STL RANK", accessor: "stl_rank" },
    { label: "BLK RANK", accessor: "blk_rank" },
    { label: "BLKA RANK", accessor: "blka_rank" },
    { label: "PF RANK", accessor: "pf_rank" },
    { label: "PFD RANK", accessor: "pfd_rank" },
    { label: "PTS RANK", accessor: "pts_rank" },
    { label: "PLUS MINUS RANK", accessor: "plus_minus_rank" }
];

const fourFactorsLineupColumns = [
    { label: "GROUP SET", accessor: "group_set" },
    { label: "GROUP ID", accessor: "group_id" },
    { label: "GROUP NAME", accessor: "group_name" },
    { label: "TEAM ID", accessor: "team_id" },
    { label: "TEAM ABBREVIATION", accessor: "team_abbreviation" },
    { label: "GP", accessor: "gp" },
    { label: "W", accessor: "w" },
    { label: "L", accessor: "l" },
    { label: "W PCT", accessor: "w_pct" },
    { label: "MIN", accessor: "min" },
    { label: "EFG PCT", accessor: "efg_pct" },
    { label: "FTA RATE", accessor: "fta_rate" },
    { label: "TM TOV PCT", accessor: "tm_tov_pct" },
    { label: "OREB PCT", accessor: "oreb_pct" },
    { label: "OPP EFG PCT", accessor: "opp_efg_pct" },
    { label: "OPP FTA RATE", accessor: "opp_fta_rate" },
    { label: "OPP TOV PCT", accessor: "opp_tov_pct" },
    { label: "OPP OREB PCT", accessor: "opp_oreb_pct" },
    { label: "GP RANK", accessor: "gp_rank" },
    { label: "W RANK", accessor: "w_rank" },
    { label: "L RANK", accessor: "l_rank" },
    { label: "W PCT RANK", accessor: "w_pct_rank" },
    { label: "MIN RANK", accessor: "min_rank" },
    { label: "EFG PCT RANK", accessor: "efg_pct_rank" },
    { label: "FTA RATE RANK", accessor: "fta_rate_rank" },
    { label: "TM TOV PCT RANK", accessor: "tm_tov_pct_rank" },
    { label: "OREB PCT RANK", accessor: "oreb_pct_rank" },
    { label: "OPP EFG PCT RANK", accessor: "opp_efg_pct_rank" },
    { label: "OPP FTA RATE RANK", accessor: "opp_fta_rate_rank" },
    { label: "OPP TOV PCT RANK", accessor: "opp_tov_pct_rank" },
    { label: "OPP OREB PCT RANK", accessor: "opp_oreb_pct_rank" }
];

const miscLineupColumns = [
    { label: "GROUP SET", accessor: "group_set" },
    { label: "GROUP ID", accessor: "group_id" },
    { label: "GROUP NAME", accessor: "group_name" },
    { label: "TEAM ID", accessor: "team_id" },
    { label: "TEAM ABBREVIATION", accessor: "team_abbreviation" },
    { label: "GP", accessor: "gp" },
    { label: "W", accessor: "w" },
    { label: "L", accessor: "l" },
    { label: "W PCT", accessor: "w_pct" },
    { label: "MIN", accessor: "min" },
    { label: "PTS OFF TOV", accessor: "pts_off_tov" },
    { label: "PTS 2ND CHANCE", accessor: "pts_2nd_chance" },
    { label: "PTS FB", accessor: "pts_fb" },
    { label: "PTS PAINT", accessor: "pts_paint" },
    { label: "OPP PTS OFF TOV", accessor: "opp_pts_off_tov" },
    { label: "OPP PTS 2ND CHANCE", accessor: "opp_pts_2nd_chance" },
    { label: "OPP PTS FB", accessor: "opp_pts_fb" },
    { label: "OPP PTS PAINT", accessor: "opp_pts_paint" },
    { label: "GP RANK", accessor: "gp_rank" },
    { label: "W RANK", accessor: "w_rank" },
    { label: "L RANK", accessor: "l_rank" },
    { label: "W PCT RANK", accessor: "w_pct_rank" },
    { label: "MIN RANK", accessor: "min_rank" },
    { label: "PTS OFF TOV RANK", accessor: "pts_off_tov_rank" },
    { label: "PTS 2ND CHANCE RANK", accessor: "pts_2nd_chance_rank" },
    { label: "PTS FB RANK", accessor: "pts_fb_rank" },
    { label: "PTS PAINT RANK", accessor: "pts_paint_rank" },
    { label: "OPP PTS OFF TOV RANK", accessor: "opp_pts_off_tov_rank" },
    { label: "OPP PTS 2ND CHANCE RANK", accessor: "opp_pts_2nd_chance_rank" },
    { label: "OPP PTS FB RANK", accessor: "opp_pts_fb_rank" },
    { label: "OPP PTS PAINT RANK", accessor: "opp_pts_paint_rank" }
];

const scoringLineupColumns = [
    { label: "GROUP SET", accessor: "group_set" },
    { label: "GROUP ID", accessor: "group_id" },
    { label: "GROUP NAME", accessor: "group_name" },
    { label: "TEAM ID", accessor: "team_id" },
    { label: "TEAM ABBREVIATION", accessor: "team_abbreviation" },
    { label: "GP", accessor: "gp" },
    { label: "W", accessor: "w" },
    { label: "L", accessor: "l" },
    { label: "W PCT", accessor: "w_pct" },
    { label: "MIN", accessor: "min" },
    { label: "PCT FGA 2PT", accessor: "pct_fga_2pt" },
    { label: "PCT FGA 3PT", accessor: "pct_fga_3pt" },
    { label: "PCT PTS 2PT", accessor: "pct_pts_2pt" },
    { label: "PCT PTS 2PT MR", accessor: "pct_pts_2pt_mr" },
    { label: "PCT PTS 3PT", accessor: "pct_pts_3pt" },
    { label: "PCT PTS FB", accessor: "pct_pts_fb" },
    { label: "PCT PTS FT", accessor: "pct_pts_ft" },
    { label: "PCT PTS OFF TOV", accessor: "pct_pts_off_tov" },
    { label: "PCT PTS PAINT", accessor: "pct_pts_paint" },
    { label: "PCT AST 2PM", accessor: "pct_ast_2pm" },
    { label: "PCT UAST 2PM", accessor: "pct_uast_2pm" },
    { label: "PCT AST 3PM", accessor: "pct_ast_3pm" },
    { label: "PCT UAST 3PM", accessor: "pct_uast_3pm" },
    { label: "PCT AST FGM", accessor: "pct_ast_fgm" },
    { label: "PCT UAST FGM", accessor: "pct_uast_fgm" },
    { label: "GP RANK", accessor: "gp_rank" },
    { label: "W RANK", accessor: "w_rank" },
    { label: "L RANK", accessor: "l_rank" },
    { label: "W PCT RANK", accessor: "w_pct_rank" },
    { label: "MIN RANK", accessor: "min_rank" },
    { label: "PCT FGA 2PT RANK", accessor: "pct_fga_2pt_rank" },
    { label: "PCT FGA 3PT RANK", accessor: "pct_fga_3pt_rank" },
    { label: "PCT PTS 2PT RANK", accessor: "pct_pts_2pt_rank" },
    { label: "PCT PTS 2PT MR RANK", accessor: "pct_pts_2pt_mr_rank" },
    { label: "PCT PTS 3PT RANK", accessor: "pct_pts_3pt_rank" },
    { label: "PCT PTS FB RANK", accessor: "pct_pts_fb_rank" },
    { label: "PCT PTS FT RANK", accessor: "pct_pts_ft_rank" },
    { label: "PCT PTS OFF TOV RANK", accessor: "pct_pts_off_tov_rank" },
    { label: "PCT PTS PAINT RANK", accessor: "pct_pts_paint_rank" },
    { label: "PCT AST 2PM RANK", accessor: "pct_ast_2pm_rank" },
    { label: "PCT UAST 2PM RANK", accessor: "pct_uast_2pm_rank" },
    { label: "PCT AST 3PM RANK", accessor: "pct_ast_3pm_rank" },
    { label: "PCT UAST 3PM RANK", accessor: "pct_uast_3pm_rank" },
    { label: "PCT AST FGM RANK", accessor: "pct_ast_fgm_rank" },
    { label: "PCT UAST FGM RANK", accessor: "pct_uast_fgm_rank" }
];

const opponentLineupColumns = [
    { label: "GROUP SET", accessor: "group_set" },
    { label: "GROUP ID", accessor: "group_id" },
    { label: "GROUP NAME", accessor: "group_name" },
    { label: "TEAM ID", accessor: "team_id" },
    { label: "TEAM ABBREVIATION", accessor: "team_abbreviation" },
    { label: "GP", accessor: "gp" },
    { label: "W", accessor: "w" },
    { label: "L", accessor: "l" },
    { label: "W PCT", accessor: "w_pct" },
    { label: "MIN", accessor: "min" },
    { label: "OPP FGM", accessor: "opp_fgm" },
    { label: "OPP FGA", accessor: "opp_fga" },
    { label: "OPP FG PCT", accessor: "opp_fg_pct" },
    { label: "OPP FG3M", accessor: "opp_fg3m" },
    { label: "OPP FG3A", accessor: "opp_fg3a" },
    { label: "OPP FG3 PCT", accessor: "opp_fg3_pct" },
    { label: "OPP FTM", accessor: "opp_ftm" },
    { label: "OPP FTA", accessor: "opp_fta" },
    { label: "OPP FT PCT", accessor: "opp_ft_pct" },
    { label: "OPP OREB", accessor: "opp_oreb" },
    { label: "OPP DREB", accessor: "opp_dreb" },
    { label: "OPP REB", accessor: "opp_reb" },
    { label: "OPP AST", accessor: "opp_ast" },
    { label: "OPP TOV", accessor: "opp_tov" },
    { label: "OPP STL", accessor: "opp_stl" },
    { label: "OPP BLK", accessor: "opp_blk" },
    { label: "OPP BLKA", accessor: "opp_blka" },
    { label: "OPP PF", accessor: "opp_pf" },
    { label: "OPP PFD", accessor: "opp_pfd" },
    { label: "OPP PTS", accessor: "opp_pts" },
    { label: "PLUS MINUS", accessor: "plus_minus" },
    { label: "GP RANK", accessor: "gp_rank" },
    { label: "W RANK", accessor: "w_rank" },
    { label: "L RANK", accessor: "l_rank" },
    { label: "W PCT RANK", accessor: "w_pct_rank" },
    { label: "MIN RANK", accessor: "min_rank" },
    { label: "OPP FGM RANK", accessor: "opp_fgm_rank" },
    { label: "OPP FGA RANK", accessor: "opp_fga_rank" },
    { label: "OPP FG PCT RANK", accessor: "opp_fg_pct_rank" },
    { label: "OPP FG3M RANK", accessor: "opp_fg3m_rank" },
    { label: "OPP FG3A RANK", accessor: "opp_fg3a_rank" },
    { label: "OPP FG3 PCT RANK", accessor: "opp_fg3_pct_rank" },
    { label: "OPP FTM RANK", accessor: "opp_ftm_rank" },
    { label: "OPP FTA RANK", accessor: "opp_fta_rank" },
    { label: "OPP FT PCT RANK", accessor: "opp_ft_pct_rank" },
    { label: "OPP OREB RANK", accessor: "opp_oreb_rank" },
    { label: "OPP DREB RANK", accessor: "opp_dreb_rank" },
    { label: "OPP REB RANK", accessor: "opp_reb_rank" },
    { label: "OPP AST RANK", accessor: "opp_ast_rank" },
    { label: "OPP TOV RANK", accessor: "opp_tov_rank" },
    { label: "OPP STL RANK", accessor: "opp_stl_rank" },
    { label: "OPP BLK RANK", accessor: "opp_blk_rank" },
    { label: "OPP BLKA RANK", accessor: "opp_blka_rank" },
    { label: "OPP PF RANK", accessor: "opp_pf_rank" },
    { label: "OPP PFD RANK", accessor: "opp_pfd1_rank" },
    { label: "OPP PTS RANK", accessor: "opp_pts_rank" },
    { label: "PLUS MINUS RANK", accessor: "plus_minus_rank" }
];


export { advancedPlayerColumns, basePlayerColumns, miscPlayerColumns, fourFactorsPlayerColumns, scoringPlayerColumns, advancedLineupColumns, baseLineupColumns, fourFactorsLineupColumns, miscLineupColumns, scoringLineupColumns, opponentLineupColumns }