const scoringPlayerColumns = [
    { label: "NAME", accessor: "player_name" },
    { label: "TEAM", accessor: "team_abbreviation" },
    { label: "MIN", accessor: "min" },
    { label: "%FGA 2PT", accessor: "pct_fga_2pt" },
    { label: "%FGA 3PT", accessor: "pct_fga_3pt" },
    { label: "%PTS 2PT", accessor: "pct_pts_2pt" },
    { label: "%PTS 2PT_MR", accessor: "pct_pts_2pt_mr" },
    { label: "%PTS 3PT", accessor: "pct_pts_3pt" },
    { label: "%PTS FB", accessor: "pct_pts_fb" },
    { label: "%PTS FT", accessor: "pct_pts_ft" },
    { label: "%PTS OFF_TOV", accessor: "pct_pts_off_tov" },
    { label: "%PTS PAINT", accessor: "pct_pts_paint" },
    { label: "%AST 2PM", accessor: "pct_ast_2pm" },
    { label: "%UAST 2PM", accessor: "pct_uast_2pm" },
    { label: "%AST 3PM", accessor: "pct_ast_3pm" },
    { label: "%UAST 3PM", accessor: "pct_uast_3pm" },
    { label: "%AST FGM", accessor: "pct_ast_fgm" },
    { label: "%UAST FGM", accessor: "pct_uast_fgm" }

];

const miscPlayerColumns = [
    { label: "NAME", accessor: "player_name" },
    { label: "TEAM", accessor: "team_abbreviation" },
    { label: "MIN", accessor: "min" },
    { label: "PTS OFF TOV", accessor: "pts_off_tov" },
    { label: "PTS 2ND CHANCE", accessor: "pts_2nd_chance" },
    { label: "PTS FB", accessor: "pts_fb" },
    { label: "PTS PAINT", accessor: "pts_paint" },
    { label: "OPP PTS OFF TOV", accessor: "opp_pts_off_tov" },
    { label: "OPP PTS 2ND CHANCE", accessor: "opp_pts_2nd_chance" },
    { label: "OPP PTS FB", accessor: "opp_pts_fb" },
    { label: "OPP PTS PAINT", accessor: "opp_pts_paint" },
    { label: "BLK", accessor: "blk" },
    { label: "BLKA", accessor: "blka" },
    { label: "PF", accessor: "pf" },
    { label: "PFD", accessor: "pfd" }
];

const fourFactorsPlayerColumns = [
    { label: "NAME", accessor: "player_name" },
    { label: "TEAM", accessor: "team_abbreviation" },
    { label: "MIN", accessor: "min" },
    { label: "EFG%", accessor: "efg_pct" },
    { label: "FTA RATE", accessor: "fta_rate" },
    { label: "TOV%", accessor: "tov_pct" },
    { label: "OREB%", accessor: "oreb_pct" }
];


const advancedPlayerColumns = [
    { label: "NAME", accessor: "player_name" },
    { label: "TEAM", accessor: "team_abbreviation" },
    { label: "MIN", accessor: "min" },
    { label: "OFF RTG", accessor: "off_rating" },
    { label: "DEF RTG", accessor: "def_rating" },
    { label: "NET RTG", accessor: "net_rating" },
    { label: "EFG%", accessor: "efg_pct" },
    { label: "TS%", accessor: "ts_pct" },
    { label: "USG%", accessor: "usg_pct" },
    { label: "AST%", accessor: "ast_pct" },
    { label: "AST TOV", accessor: "ast_tov" },
    { label: "AST RATIO", accessor: "ast_ratio" },
    { label: "OREB%", accessor: "oreb_pct" },
    { label: "DEF REB%", accessor: "dreb_pct" },
    { label: "REB%", accessor: "reb_pct" },
    { label: "TOV%", accessor: "tov_pct" },
    { label: "POSS", accessor: "poss" },
    { label: "PIE", accessor: "pie" }
]

const basePlayerColumns = [
    { label: "NAME", accessor: "player_name" },
    { label: "TEAM", accessor: "team_abbreviation" },
    { label: "MIN", accessor: "min" },
    { label: "PTS", accessor: "pts" },
    { label: "REB", accessor: "reb" },
    { label: "AST", accessor: "ast" },
    { label: "STL", accessor: "stl" },
    { label: "BLK", accessor: "blk" },
    { label: "TOV", accessor: "tov" },
    { label: "OREB", accessor: "oreb" },
    { label: "DREB", accessor: "dreb" },
    { label: "FGM", accessor: "fgm" },
    { label: "FGA", accessor: "fga" },
    { label: "FG%", accessor: "fg_pct" },
    { label: "FG3M", accessor: "fg3m" },
    { label: "FG3A", accessor: "fg3a" },
    { label: "FG3%", accessor: "fg3_pct" },
    { label: "FTM", accessor: "ftm" },
    { label: "FTA", accessor: "fta" },
    { label: "FT%", accessor: "ft_pct" },
    { label: "PF", accessor: "pf" },
    { label: "+/-", accessor: "plus_minus" }
];

const basePlayerColumnsNoName = [
    { label: "MATCHUP", accessor: "matchup" },
    { label: "DATE", accessor: "game_date"},
    { label: "MIN", accessor: "min" },
    { label: "PTS", accessor: "pts" },
    { label: "REB", accessor: "reb" },
    { label: "AST", accessor: "ast" },
    { label: "STL", accessor: "stl" },
    { label: "BLK", accessor: "blk" },
    { label: "TOV", accessor: "tov" },
    { label: "OREB", accessor: "oreb" },
    { label: "DREB", accessor: "dreb" },
    { label: "FGM", accessor: "fgm" },
    { label: "FGA", accessor: "fga" },
    { label: "FG%", accessor: "fg_pct" },
    { label: "FG3M", accessor: "fg3m" },
    { label: "FG3A", accessor: "fg3a" },
    { label: "FG3%", accessor: "fg3_pct" },
    { label: "FTM", accessor: "ftm" },
    { label: "FTA", accessor: "fta" },
    { label: "FT%", accessor: "ft_pct" },
    { label: "PF", accessor: "pf" },
    { label: "+/-", accessor: "plus_minus" }
];

const advancedLineupColumns = [
    { label: "GROUP NAME", accessor: "group_name" },
    { label: "TEAM", accessor: "team_abbreviation" },
    { label: "GP", accessor: "gp" },
    { label: "W", accessor: "w" },
    { label: "L", accessor: "l" },
    { label: "W%", accessor: "w_pct" },
    { label: "MIN", accessor: "min" },
    { label: "E OFF RTG", accessor: "e_off_rating" },
    { label: "OFF RTG", accessor: "off_rating" },
    { label: "E DEF RTG", accessor: "e_def_rating" },
    { label: "DEF RTG", accessor: "def_rating" },
    { label: "E NET RTG", accessor: "e_net_rating" },
    { label: "NET RTG", accessor: "net_rating" },
    { label: "AST%", accessor: "ast_pct" },
    { label: "AST TO", accessor: "ast_to" },
    { label: "AST RATIO", accessor: "ast_ratio" },
    { label: "OREB%", accessor: "oreb_pct" },
    { label: "DREB%", accessor: "dreb_pct" },
    { label: "REB%", accessor: "reb_pct" },
    { label: "TM TOV%", accessor: "tm_tov_pct" },
    { label: "EFG%", accessor: "efg_pct" },
    { label: "TS%", accessor: "ts_pct" },
    { label: "E PACE", accessor: "e_pace" },
    { label: "PACE", accessor: "pace" },
    { label: "PACE PER40", accessor: "pace_per40" },
    { label: "POSS", accessor: "poss" },
    { label: "PIE", accessor: "pie" },
    { label: "GP RANK", accessor: "gp_rank" },
    { label: "W RANK", accessor: "w_rank" },
    { label: "L RANK", accessor: "l_rank" },
    { label: "W% RANK", accessor: "w_pct_rank" },
    { label: "MIN RANK", accessor: "min_rank" },
    { label: "OFF RTG RANK", accessor: "off_rating_rank" },
    { label: "DEF RTG RANK", accessor: "def_rating_rank" },
    { label: "NET RTG RANK", accessor: "net_rating_rank" },
    { label: "AST% RANK", accessor: "ast_pct_rank" },
    { label: "AST TO RANK", accessor: "ast_to_rank" },
    { label: "AST RATIO RANK", accessor: "ast_ratio_rank" },
    { label: "OREB% RANK", accessor: "oreb_pct_rank" },
    { label: "DREB% RANK", accessor: "dreb_pct_rank" },
    { label: "REB% RANK", accessor: "reb_pct_rank" },
    { label: "TM TOV% RANK", accessor: "tm_tov_pct_rank" },
    { label: "EFG% RANK", accessor: "efg_pct_rank" },
    { label: "TS% RANK", accessor: "ts_pct_rank" },
    { label: "PACE RANK", accessor: "pace_rank" },
    { label: "PIE RANK", accessor: "pie_rank" }
]

const baseLineupColumns = [
    { label: "GROUP NAME", accessor: "group_name" },
    { label: "TEAM", accessor: "team_abbreviation" },
    { label: "GP", accessor: "gp" },
    { label: "W", accessor: "w" },
    { label: "L", accessor: "l" },
    { label: "W%", accessor: "w_pct" },
    { label: "MIN", accessor: "min" },
    { label: "PTS", accessor: "pts" },
    { label: "REB", accessor: "reb" },
    { label: "AST", accessor: "ast" },
    { label: "TOV", accessor: "tov" },
    { label: "STL", accessor: "stl" },
    { label: "BLK", accessor: "blk" },
    { label: "OREB", accessor: "oreb" },
    { label: "DREB", accessor: "dreb" },
    { label: "FGM", accessor: "fgm" },
    { label: "FGA", accessor: "fga" },
    { label: "FG%", accessor: "fg_pct" },
    { label: "FG3M", accessor: "fg3m" },
    { label: "FG3A", accessor: "fg3a" },
    { label: "FG3%", accessor: "fg3_pct" },
    { label: "FTM", accessor: "ftm" },
    { label: "FTA", accessor: "fta" },
    { label: "FT%", accessor: "ft_pct" },
    { label: "BLKA", accessor: "blka" },
    { label: "PF", accessor: "pf" },
    { label: "PFD", accessor: "pfd" },
    { label: "+/-", accessor: "plus_minus" },
    { label: "GP RANK", accessor: "gp_rank" },
    { label: "W RANK", accessor: "w_rank" },
    { label: "L RANK", accessor: "l_rank" },
    { label: "W% RANK", accessor: "w_pct_rank" },
    { label: "MIN RANK", accessor: "min_rank" },
    { label: "FGM RANK", accessor: "fgm_rank" },
    { label: "FGA RANK", accessor: "fga_rank" },
    { label: "FG% RANK", accessor: "fg_pct_rank" },
    { label: "FG3M RANK", accessor: "fg3m_rank" },
    { label: "FG3A RANK", accessor: "fg3a_rank" },
    { label: "FG3% RANK", accessor: "fg3_pct_rank" },
    { label: "FTM RANK", accessor: "ftm_rank" },
    { label: "FTA RANK", accessor: "fta_rank" },
    { label: "FT% RANK", accessor: "ft_pct_rank" },
    { label: "OREB RANK", accessor: "oreb_rank" },
    { label: "DREB RANK", accessor: "dreb_rank" },
    { label: "REB RANK", accessor: "reb_rank" },
    { label: "AST RANK", accessor: "ast_rank" },
    { label: "TOV RANK", accessor: "tov_rank" },
    { label: "STL RANK", accessor: "stl_rank" },
    { label: "BLK RANK", accessor: "blk_rank" },
    { label: "BLKA RANK", accessor: "blka_rank" },
    { label: "PF RANK", accessor: "pf_rank" },
    { label: "PFD RANK", accessor: "pfd_rank" },
    { label: "PTS RANK", accessor: "pts_rank" },
    { label: "+/- RANK", accessor: "plus_minus_rank" }
];

const fourFactorsLineupColumns = [
    { label: "GROUP NAME", accessor: "group_name" },
    { label: "TEAM", accessor: "team_abbreviation" },
    { label: "GP", accessor: "gp" },
    { label: "W", accessor: "w" },
    { label: "L", accessor: "l" },
    { label: "W%", accessor: "w_pct" },
    { label: "MIN", accessor: "min" },
    { label: "EFG%", accessor: "efg_pct" },
    { label: "FTA RATE", accessor: "fta_rate" },
    { label: "TM TOV%", accessor: "tm_tov_pct" },
    { label: "OREB%", accessor: "oreb_pct" },
    { label: "OPP EFG%", accessor: "opp_efg_pct" },
    { label: "OPP FTA RATE", accessor: "opp_fta_rate" },
    { label: "OPP TOV%", accessor: "opp_tov_pct" },
    { label: "OPP OREB%", accessor: "opp_oreb_pct" },
    { label: "GP RANK", accessor: "gp_rank" },
    { label: "W RANK", accessor: "w_rank" },
    { label: "L RANK", accessor: "l_rank" },
    { label: "W% RANK", accessor: "w_pct_rank" },
    { label: "MIN RANK", accessor: "min_rank" },
    { label: "EFG% RANK", accessor: "efg_pct_rank" },
    { label: "FTA RATE RANK", accessor: "fta_rate_rank" },
    { label: "TM TOV% RANK", accessor: "tm_tov_pct_rank" },
    { label: "OREB% RANK", accessor: "oreb_pct_rank" },
    { label: "OPP EFG% RANK", accessor: "opp_efg_pct_rank" },
    { label: "OPP FTA RATE RANK", accessor: "opp_fta_rate_rank" },
    { label: "OPP TOV% RANK", accessor: "opp_tov_pct_rank" },
    { label: "OPP OREB% RANK", accessor: "opp_oreb_pct_rank" }
];

const miscLineupColumns = [
    { label: "GROUP NAME", accessor: "group_name" },
    { label: "TEAM", accessor: "team_abbreviation" },
    { label: "GP", accessor: "gp" },
    { label: "W", accessor: "w" },
    { label: "L", accessor: "l" },
    { label: "W%", accessor: "w_pct" },
    { label: "MIN", accessor: "min" },
    { label: "PTS OFF TOV", accessor: "pts_off_tov" },
    { label: "PTS 2ND CHANCE", accessor: "pts_2nd_chance" },
    { label: "PTS FB", accessor: "pts_fb" },
    { label: "PTS PAINT", accessor: "pts_paint" },
    { label: "OPP PTS OFF TOV", accessor: "opp_pts_off_tov" },
    { label: "OPP PTS 2ND CHANCE", accessor: "opp_pts_2nd_chance" },
    { label: "OPP PTS FB", accessor: "opp_pts_fb" },
    { label: "OPP PTS PAINT", accessor: "opp_pts_paint" },
    { label: "GP RANK", accessor: "gp_rank" },
    { label: "W RANK", accessor: "w_rank" },
    { label: "L RANK", accessor: "l_rank" },
    { label: "W% RANK", accessor: "w_pct_rank" },
    { label: "MIN RANK", accessor: "min_rank" },
    { label: "PTS OFF TOV RANK", accessor: "pts_off_tov_rank" },
    { label: "PTS 2ND CHANCE RANK", accessor: "pts_2nd_chance_rank" },
    { label: "PTS FB RANK", accessor: "pts_fb_rank" },
    { label: "PTS PAINT RANK", accessor: "pts_paint_rank" },
    { label: "OPP PTS OFF TOV RANK", accessor: "opp_pts_off_tov_rank" },
    { label: "OPP PTS 2ND CHANCE RANK", accessor: "opp_pts_2nd_chance_rank" },
    { label: "OPP PTS FB RANK", accessor: "opp_pts_fb_rank" },
    { label: "OPP PTS PAINT RANK", accessor: "opp_pts_paint_rank" }
];

const scoringLineupColumns = [
    { label: "GROUP NAME", accessor: "group_name" },
    { label: "TEAM", accessor: "team_abbreviation" },
    { label: "GP", accessor: "gp" },
    { label: "W", accessor: "w" },
    { label: "L", accessor: "l" },
    { label: "W%", accessor: "w_pct" },
    { label: "MIN", accessor: "min" },
    { label: "%FGA 2PT", accessor: "pct_fga_2pt" },
    { label: "%FGA 3PT", accessor: "pct_fga_3pt" },
    { label: "%PTS 2PT", accessor: "pct_pts_2pt" },
    { label: "%PTS 2PT MR", accessor: "pct_pts_2pt_mr" },
    { label: "%PTS 3PT", accessor: "pct_pts_3pt" },
    { label: "%PTS FB", accessor: "pct_pts_fb" },
    { label: "%PTS FT", accessor: "pct_pts_ft" },
    { label: "%PTS OFF TOV", accessor: "pct_pts_off_tov" },
    { label: "%PTS PAINT", accessor: "pct_pts_paint" },
    { label: "%AST 2PM", accessor: "pct_ast_2pm" },
    { label: "%UAST 2PM", accessor: "pct_uast_2pm" },
    { label: "%AST 3PM", accessor: "pct_ast_3pm" },
    { label: "%UAST 3PM", accessor: "pct_uast_3pm" },
    { label: "%AST FGM", accessor: "pct_ast_fgm" },
    { label: "%UAST FGM", accessor: "pct_uast_fgm" },
    { label: "GP RANK", accessor: "gp_rank" },
    { label: "W RANK", accessor: "w_rank" },
    { label: "L RANK", accessor: "l_rank" },
    { label: "W% RANK", accessor: "w_pct_rank" },
    { label: "MIN RANK", accessor: "min_rank" },
    { label: "%FGA 2PT RANK", accessor: "pct_fga_2pt_rank" },
    { label: "%FGA 3PT RANK", accessor: "pct_fga_3pt_rank" },
    { label: "%PTS 2PT RANK", accessor: "pct_pts_2pt_rank" },
    { label: "%PTS 2PT MR RANK", accessor: "pct_pts_2pt_mr_rank" },
    { label: "%PTS 3PT RANK", accessor: "pct_pts_3pt_rank" },
    { label: "%PTS FB RANK", accessor: "pct_pts_fb_rank" },
    { label: "%PTS FT RANK", accessor: "pct_pts_ft_rank" },
    { label: "%PTS OFF TOV RANK", accessor: "pct_pts_off_tov_rank" },
    { label: "%PTS PAINT RANK", accessor: "pct_pts_paint_rank" },
    { label: "%AST 2PM RANK", accessor: "pct_ast_2pm_rank" },
    { label: "%UAST 2PM RANK", accessor: "pct_uast_2pm_rank" },
    { label: "%AST 3PM RANK", accessor: "pct_ast_3pm_rank" },
    { label: "%UAST 3PM RANK", accessor: "pct_uast_3pm_rank" },
    { label: "%AST FGM RANK", accessor: "pct_ast_fgm_rank" },
    { label: "%UAST FGM RANK", accessor: "pct_uast_fgm_rank" }
];

const opponentLineupColumns = [
    { label: "GROUP NAME", accessor: "group_name" },
    { label: "TEAM", accessor: "team_abbreviation" },
    { label: "GP", accessor: "gp" },
    { label: "W", accessor: "w" },
    { label: "L", accessor: "l" },
    { label: "W%", accessor: "w_pct" },
    { label: "MIN", accessor: "min" },
    { label: "OPP FGM", accessor: "opp_fgm" },
    { label: "OPP FGA", accessor: "opp_fga" },
    { label: "OPP FG%", accessor: "opp_fg_pct" },
    { label: "OPP FG3M", accessor: "opp_fg3m" },
    { label: "OPP FG3A", accessor: "opp_fg3a" },
    { label: "OPP FG3%", accessor: "opp_fg3_pct" },
    { label: "OPP FTM", accessor: "opp_ftm" },
    { label: "OPP FTA", accessor: "opp_fta" },
    { label: "OPP FT%", accessor: "opp_ft_pct" },
    { label: "OPP OREB", accessor: "opp_oreb" },
    { label: "OPP DREB", accessor: "opp_dreb" },
    { label: "OPP REB", accessor: "opp_reb" },
    { label: "OPP AST", accessor: "opp_ast" },
    { label: "OPP TOV", accessor: "opp_tov" },
    { label: "OPP STL", accessor: "opp_stl" },
    { label: "OPP BLK", accessor: "opp_blk" },
    { label: "OPP BLKA", accessor: "opp_blka" },
    { label: "OPP PF", accessor: "opp_pf" },
    { label: "OPP PFD", accessor: "opp_pfd" },
    { label: "OPP PTS", accessor: "opp_pts" },
    { label: "+/-", accessor: "plus_minus" },
    { label: "GP RANK", accessor: "gp_rank" },
    { label: "W RANK", accessor: "w_rank" },
    { label: "L RANK", accessor: "l_rank" },
    { label: "W% RANK", accessor: "w_pct_rank" },
    { label: "MIN RANK", accessor: "min_rank" },
    { label: "OPP FGM RANK", accessor: "opp_fgm_rank" },
    { label: "OPP FGA RANK", accessor: "opp_fga_rank" },
    { label: "OPP FG% RANK", accessor: "opp_fg_pct_rank" },
    { label: "OPP FG3M RANK", accessor: "opp_fg3m_rank" },
    { label: "OPP FG3A RANK", accessor: "opp_fg3a_rank" },
    { label: "OPP FG3% RANK", accessor: "opp_fg3_pct_rank" },
    { label: "OPP FTM RANK", accessor: "opp_ftm_rank" },
    { label: "OPP FTA RANK", accessor: "opp_fta_rank" },
    { label: "OPP FT% RANK", accessor: "opp_ft_pct_rank" },
    { label: "OPP OREB RANK", accessor: "opp_oreb_rank" },
    { label: "OPP DREB RANK", accessor: "opp_dreb_rank" },
    { label: "OPP REB RANK", accessor: "opp_reb_rank" },
    { label: "OPP AST RANK", accessor: "opp_ast_rank" },
    { label: "OPP TOV RANK", accessor: "opp_tov_rank" },
    { label: "OPP STL RANK", accessor: "opp_stl_rank" },
    { label: "OPP BLK RANK", accessor: "opp_blk_rank" },
    { label: "OPP BLKA RANK", accessor: "opp_blka_rank" },
    { label: "OPP PF RANK", accessor: "opp_pf_rank" },
    { label: "OPP PFD RANK", accessor: "opp_pfd1_rank" },
    { label: "OPP PTS RANK", accessor: "opp_pts_rank" },
    { label: "+/- RANK", accessor: "plus_minus_rank" }
];

const mlbBattingColumnsSorting = [
    { label: "Name", accessor: "full_name" },
    { label: "Team", accessor: "team_name" },
    { label: "LG", accessor: "league_name"},
    { label: "GP", accessor: "games_played" },
    { label: "AB", accessor: "at_bats" },
    { label: "H", accessor: "hits" },
    { label: "R", accessor: "runs" },
    { label: "HR", accessor: "home_runs" },
    { label: "RBI", accessor: "rbi" },
    { label: "AVG", accessor: "average" },
    { label: "SB", accessor: "stolen_bases" },
    { label: "CS", accessor: "caught_stealing" },
    { label: "SB%", accessor: "stolen_base_percentage" },
    { label: "TB", accessor: "total_bases" },
    { label: "FO", accessor: "fly_outs" },
    { label: "GO", accessor: "ground_outs" },
    //{ label: "Air Outs", accessor: "airOuts" },
    { label: "PO", accessor: "pop_outs" },
    { label: "LO", accessor: "line_outs" },
    { label: "2B", accessor: "doubles" },
    { label: "3B", accessor: "triples" },
    { label: "K", accessor: "strike_outs" },
    { label: "BB", accessor: "base_on_balls" },
    { label: "IBB", accessor: "intentional_walks" },
    { label: "HBP", accessor: "hit_by_pitch" },
    { label: "GIDP", accessor: "ground_into_double_play" },
    { label: "GITP", accessor: "ground_into_triple_play" },
    { label: "PA", accessor: "plate_appearances" },
    { label: "LOB", accessor: "left_on_base" },
    { label: "SAC", accessor: "sac_bunts" },
    { label: "SF", accessor: "sac_flies" },
    { label: "CI", accessor: "catchers_interference" },
    { label: "PK", accessor: "pickoffs" },
    { label: "AB/HR", accessor: "at_bats_per_home_run" },
    { label: "OBP", accessor: "obp" },
    { label: "SLG", accessor: "slg" },
    { label: "OPS", accessor: "ops" }
];

const mlbBattingColumns = [
    { label: "Name", accessor: "fullName" },
    { label: "Team", accessor: "teamName" },
    { label: "LG", accessor: "leagueName"},
    { label: "GP", accessor: "gamesPlayed" },
    { label: "AB", accessor: "atBats" },
    { label: "H", accessor: "hits" },
    { label: "R", accessor: "runs" },
    { label: "HR", accessor: "homeRuns" },
    { label: "RBI", accessor: "rbi" },
    { label: "AVG", accessor: "average" },
    { label: "SB", accessor: "stolenBases" },
    { label: "CS", accessor: "caughtStealing" },
    { label: "SB%", accessor: "stolenBasePercentage" },
    { label: "TB", accessor: "totalBases" },
    { label: "FO", accessor: "flyOuts" },
    { label: "GO", accessor: "groundOuts" },
    //{ label: "Air Outs", accessor: "airOuts" },
    { label: "PO", accessor: "popOuts" },
    { label: "LO", accessor: "lineOuts" },
    { label: "2B", accessor: "doubles" },
    { label: "3B", accessor: "triples" },
    { label: "K", accessor: "strikeOuts" },
    { label: "BB", accessor: "baseOnBalls" },
    { label: "IBB", accessor: "intentionalWalks" },
    { label: "HBP", accessor: "hitByPitch" },
    { label: "GIDP", accessor: "groundIntoDoublePlay" },
    { label: "GITP", accessor: "groundIntoTriplePlay" },
    { label: "PA", accessor: "plateAppearances" },
    { label: "LOB", accessor: "leftOnBase" },
    { label: "SAC", accessor: "sacBunts" },
    { label: "SF", accessor: "sacFlies" },
    { label: "CI", accessor: "catchersInterference" },
    { label: "PK", accessor: "pickoffs" },
    { label: "AB/HR", accessor: "atBatsPerHomeRun" },
    { label: "OBP", accessor: "obp" },
    { label: "SLG", accessor: "slg" },
    { label: "OPS", accessor: "ops" }
];

const mlbBattingColumnsPropBet = [
    { label: "Matchup", accessor: "matchup" },
    { label: "Date", accessor: "gameDate" },
    { label: "AB", accessor: "atBats" },
    { label: "H", accessor: "hits" },
    { label: "R", accessor: "runs" },
    { label: "HR", accessor: "homeRuns" },
    { label: "RBI", accessor: "rbi" },
    { label: "AVG", accessor: "average" },
    { label: "SB", accessor: "stolenBases" },
    { label: "CS", accessor: "caughtStealing" },
    { label: "SB%", accessor: "stolenBasePercentage" },
    { label: "TB", accessor: "totalBases" },
    { label: "FO", accessor: "flyOuts" },
    { label: "GO", accessor: "groundOuts" },
    //{ label: "Air Outs", accessor: "airOuts" },
    { label: "PO", accessor: "popOuts" },
    { label: "LO", accessor: "lineOuts" },
    { label: "2B", accessor: "doubles" },
    { label: "3B", accessor: "triples" },
    { label: "K", accessor: "strikeOuts" },
    { label: "BB", accessor: "baseOnBalls" },
    { label: "IBB", accessor: "intentionalWalks" },
    { label: "HBP", accessor: "hitByPitch" },
    { label: "GIDP", accessor: "groundIntoDoublePlay" },
    { label: "GITP", accessor: "groundIntoTriplePlay" },
    { label: "PA", accessor: "plateAppearances" },
    { label: "LOB", accessor: "leftOnBase" },
    { label: "SAC", accessor: "sacBunts" },
    { label: "SF", accessor: "sacFlies" },
    { label: "CI", accessor: "catchersInterference" },
    { label: "PK", accessor: "pickoffs" },
    { label: "AB/HR", accessor: "atBatsPerHomeRun" },
    { label: "OBP", accessor: "obp" },
    { label: "SLG", accessor: "slg" },
    { label: "OPS", accessor: "ops" }
];

const mlbPitchingColumns = [
    { label: "Player", accessor: "fullName" },
    { label: "Team", accessor: "teamName" },
    { label: "LG", accessor: "leagueName" },
    { label: "W", accessor: "wins" },
    { label: "L", accessor: "losses" },
    { label: "GP", accessor: "gamesPlayed" },
    { label: "GS", accessor: "gamesStarted" },
    //{ label: "Games Pitched", accessor: "gamesPitched" },
    { label: "CG", accessor: "completeGames" },
    { label: "SHO", accessor: "shutouts" },
    { label: "SV", accessor: "saves" },
    { label: "SVO", accessor: "saveOpportunities" },
    { label: "IP", accessor: "inningsPitched" },
    { label: "H", accessor: "hits" },
    { label: "R", accessor: "runs" },
    { label: "ER", accessor: "earnedRuns" },
    { label: "HR", accessor: "homeRuns" },
    { label: "HBP", accessor: "hitBatsmen" },
    { label: "BB", accessor: "baseOnBalls" },
    { label: "K", accessor: "strikeOuts" },
    { label: "ERA", accessor: "era" },
    { label: "WHIP", accessor: "whip" }, 
    { label: "AVG", accessor: "average" },

    { label: "TBF", accessor: "battersFaced" },
    { label: "PT", accessor: "pitchesThrown" },
    { label: "HLD", accessor: "holds" },
    { label: "2B", accessor: "doubles" },
    { label: "3B", accessor: "triples" },
    { label: "IBB", accessor: "intentionalWalks" },
    { label: "Runs/9", accessor: "runsScoredPer9" },
    { label: "HR/9", accessor: "homeRunsPer9" },
    { label: "K/9", accessor: "strikeoutsPer9" },
    { label: "BB/9", accessor: "walksPer9" },
    //{ label: "At Bats", accessor: "atBats" },

    { label: "FO", accessor: "flyOuts" },
    { label: "GO", accessor: "groundOuts" },
    //{ label: "Air Outs", accessor: "airOuts" },
    { label: "PO", accessor: "popOuts" },
    { label: "LO", accessor: "lineOuts" },
    //{ label: "Balls", accessor: "balls" },
    //{ label: "Strikes", accessor: "strikes" },
    //{ label: "Strike %", accessor: "strikePercentage" },
    //{ label: "Wild Pitches", accessor: "wildPitches" },
    //{ label: "Balks", accessor: "balks" },
    //{ label: "GF", accessor: "gamesFinished" },
    { label: "IR", accessor: "inheritedRunners" },
    { label: "IRS", accessor: "inheritedRunnersScored" },
    { label: "Sac", accessor: "sacBunts" },
    { label: "SF", accessor: "sacFlies" },
    { label: "CI", accessor: "catchersInterference" },
    { label: "CS", accessor: "caughtStealing" },
    { label: "SB", accessor: "stolenBases" },
    { label: "PK", accessor: "pickoffs" },
    { label: "PB", accessor: "passedBalls" },
    { label: "Outs", accessor: "outs" }
];

const mlbPitchingColumnsPropBet = [
    { label: "Matchup", accessor: "matchup" },
    { label: "Date", accessor: "gameDate" },
    { label: "W", accessor: "wins" },
    { label: "L", accessor: "losses" },
    { label: "GS", accessor: "gamesStarted" },
    //{ label: "Games Pitched", accessor: "gamesPitched" },
    { label: "CG", accessor: "completeGames" },
    { label: "SHO", accessor: "shutouts" },
    { label: "SV", accessor: "saves" },
    { label: "SVO", accessor: "saveOpportunities" },
    { label: "IP", accessor: "inningsPitched" },
    { label: "H", accessor: "hits" },
    { label: "R", accessor: "runs" },
    { label: "ER", accessor: "earnedRuns" },
    { label: "HR", accessor: "homeRuns" },
    { label: "HBP", accessor: "hitBatsmen" },
    { label: "BB", accessor: "baseOnBalls" },
    { label: "K", accessor: "strikeOuts" },
    { label: "ERA", accessor: "era" },
    { label: "WHIP", accessor: "whip" }, 
    { label: "AVG", accessor: "average" },

    { label: "TBF", accessor: "battersFaced" },
    { label: "PT", accessor: "pitchesThrown" },
    { label: "HLD", accessor: "holds" },
    { label: "2B", accessor: "doubles" },
    { label: "3B", accessor: "triples" },
    { label: "IBB", accessor: "intentionalWalks" },
    { label: "Runs/9", accessor: "runsScoredPer9" },
    { label: "HR/9", accessor: "homeRunsPer9" },
    { label: "K/9", accessor: "strikeoutsPer9" },
    { label: "BB/9", accessor: "walksPer9" },
    //{ label: "At Bats", accessor: "atBats" },

    { label: "FO", accessor: "flyOuts" },
    { label: "GO", accessor: "groundOuts" },
    //{ label: "Air Outs", accessor: "airOuts" },
    { label: "PO", accessor: "popOuts" },
    { label: "LO", accessor: "lineOuts" },
    //{ label: "Balls", accessor: "balls" },
    //{ label: "Strikes", accessor: "strikes" },
    //{ label: "Strike %", accessor: "strikePercentage" },
    //{ label: "Wild Pitches", accessor: "wildPitches" },
    //{ label: "Balks", accessor: "balks" },
    //{ label: "GF", accessor: "gamesFinished" },
    { label: "IR", accessor: "inheritedRunners" },
    { label: "IRS", accessor: "inheritedRunnersScored" },
    { label: "Sac", accessor: "sacBunts" },
    { label: "SF", accessor: "sacFlies" },
    { label: "CI", accessor: "catchersInterference" },
    { label: "CS", accessor: "caughtStealing" },
    { label: "SB", accessor: "stolenBases" },
    { label: "PK", accessor: "pickoffs" },
    { label: "PB", accessor: "passedBalls" },
    { label: "Outs", accessor: "outs" }
];



export { advancedPlayerColumns, basePlayerColumns, miscPlayerColumns, fourFactorsPlayerColumns, scoringPlayerColumns, advancedLineupColumns, baseLineupColumns, fourFactorsLineupColumns, miscLineupColumns, scoringLineupColumns, opponentLineupColumns, basePlayerColumnsNoName, 
    mlbBattingColumns, mlbBattingColumnsSorting, mlbPitchingColumns, mlbBattingColumnsPropBet, mlbPitchingColumnsPropBet }