export interface MLBPlayerGamePitching {
    gamePk: number;
    teamSide: string;
    teamName: string;
    teamId: number;
    playerId: string;
    personId: number | null;
    note: string;
    summary: string;
    gamesPlayed: number | null;
    gamesStarted: number | null;
    flyOuts: number | null;
    groundOuts: number | null;
    airOuts: number | null;
    runs: number | null;
    doubles: number | null;
    triples: number | null;
    homeRuns: number | null;
    strikeOuts: number | null;
    baseOnBalls: number | null;
    intentionalWalks: number | null;
    hits: number | null;
    hitByPitch: number | null;
    atBats: number | null;
    caughtStealing: number | null;
    stolenBases: number | null;
    stolenBasePercentage: number | null;
    numberOfPitches: number | null;
    inningsPitched: string;
    wins: number | null;
    losses: number | null;
    saves: number | null;
    saveOpportunities: number | null;
    holds: number | null;
    blownSaves: number | null;
    earnedRuns: number | null;
    battersFaced: number | null;
    outs: number | null;
    gamesPitched: number | null;
    completeGames: number | null;
    shutouts: number | null;
    pitchesThrown: number | null;
    balls: number | null;
    strikes: number | null;
    strikePercentage: string;
    hitBatsmen: number | null;
    balks: number | null;
    wildPitches: number | null;
    pickoffs: number | null;
    rbi: number | null;
    gamesFinished: number | null;
    runsScoredPer9: number | null;
    homeRunsPer9: number | null;
    inheritedRunners: number | null;
    inheritedRunnersScored: number | null;
    catchersInterference: number | null;
    sacBunts: number | null;
    sacFlies: number | null;
    passedBall: number | null;
    popOuts: number | null;
    lineOuts: number | null;
}
