export interface MLBPlayerGameBatting {
    gamePk: number;
    teamSide: string;
    teamName: string;
    playerId: string;
    personId: number | null;
    fullName: string
    position: string;
    positionAbbr: string;
    summary: string;
    gamesPlayed: number | null;
    flyOuts: number | null;
    groundOuts: number | null;
    airOuts: number | null;
    runs: number | null;
    doubles: number | null;
    triples: number | null;
    homeRuns: number | null;
    strikeOuts: number | null;
    baseOnBalls: number | null;
    intentionalWalks: number | null;
    hits: number | null;
    hitByPitch: number | null;
    atBats: number | null;
    caughtStealing: number | null;
    stolenBases: number | null;
    stolenBasePercentage: number | null;
    groundIntoDoublePlay: number | null;
    groundIntoTriplePlay: number | null;
    plateAppearances: number | null;
    totalBases: number | null;
    rbi: number | null;
    leftOnBase: number | null;
    sacBunts: number | null;
    sacFlies: number | null;
    catchersInterference: number | null;
    pickoffs: number | null;
    atBatsPerHomeRun: string;
    popOuts: number | null;
    lineOuts: number | null;
    note: string;
    obp: number | null;
    slg: number | null;
    ops: number | null;
}
